name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install mustache
        run: apk add ruby && gem install mustache

      - name: Run Build Script
        run: sh ./build.sh

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@develop
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEOKIVE_KEY }}
        with:
          source-directory: "output"
          destination-github-username: ${{ secrets.DEOKIVE_USERNAME }}
          destination-repository-name: ${{ secrets.DEOKIVE_REPOSITORY }}
          user-email: ${{ secrets.DEOKIVE_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: develop

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
